### ISSUE TITLE
Unable to add a directory. Build #223

### ISSUE THREAD

**Issue by DaniWe** [sba1/simplegit#1]
Can add files but not directories. Files in directories are also ok. Commit, log and show works when commiting the files I could add.

> sgit add Annotate_src.readme
> sgit add Annotate_src.readme.info
> sgit add src
> libgit error (2): Could not find '/Project/UpLoad/Deniil715Pack/git/Annotate_src/src' to open: Not a directory
> sgit add .
> . is outside repository!
> sgit add src/ann.h
> sgit add src/Makefile

**Comment by sba1** [comment]
Adding directories including the root of the git repo should work now. This was addressed in commit bd4a70bbfd25b26bb7941d10d189b88251f379ee.

**Comment by DaniWe** [comment]
Thank you very much. Now it seems I can start to version handle all my sources on the Amiga.

**Comment by sba1** [comment]
Okay, thanks for testing. Closing it now. Feel free to open a new one if something doesn't work as expected.
