### ISSUE TITLE
lack of "pull" operation as orthogonal function to push

### ISSUE THREAD

**Issue by ghost** [sba1/simplegit#11]
I was happy when I was using simplegit without collaboration,  but now that I am...

Pull as an operational verb has become a required operation.
along with input validation of the majority of the non-trivial commandset.

an additional bug is that file in the checkout fail to be sync'ed with remote changes as deltas
are apparently ignored when trying to fetch and merge changes.

I am repeatedly seeing the first copy checked in by whomever pushed the file first without any updated content applied.

what workflow support is there?

**Comment by sba1** [comment]
For pull, you can do a fetch and a rebase or merge depending on your needs.

For the other stuff, please mention some examples and file separate issues.

**Comment by ghost** [comment]
I attempted fetch+merge / fetch+rebase / fetch+merge+rebase as combinations and was NOT shown updated sources in any case.

even despite such update attempts I was forced to git pull on a linux hosted copy and then re-clone that by tarball and copy from a raspberrypi to actually regain a working source tree that was aable to push changes again.

alternate workflows are not 100% reliable in this functionality.

**Comment by sba1** [comment]
Of course, git fetch and a proper git merge is 100% the same as git pull.

Please supply the exact command line and the result of the command. At least the very basic merge should work also with simplegit.

**Comment by ghost** [comment]
sgit fetch origin
sgit merge master
sgit rebase master

exact commands in that order,

on disk changes of known modified sources is zero,  the files in question are reset to the last local push state or first from remote state without updates applied.

I'm not familiar with git being used beyond the primary add push pull and rm functionality on other systems.

Each time I have run into this I have had to re-clone the entire repository to resync or copy from the raspberrypi.

this has only become a problem due to adding a collaborator to the Perception-IME project as found here on github under my own user account.

I'm writing these comments using an Android tablet and not my AOS4 machine where I develop code

would adding a photograph of the screen when running the commands concerned help?

**Comment by Belxjander** [comment]
Each time I have run into this I have had to re-clone the entire repository to resync or copy from the raspberrypi.

this has only become a problem due to adding a collaborator to the Perception-IME project as found here on github under my own user account.

**Comment by sba1** [comment]
For applying changes from the origin branches, use sgit merge origin/master or sgit rebase origin/master.

**Comment by ghost** [comment]
again...

sgit fetch origin
sgit merge origin/master -->> libgit error (4) Reference 'origin/master' not found

> > sgit merge master<< THIS executes without the above error including "origin" breaks.
> > same issue with "rebase"

the instructions you have given match what I have tried which has to date been unsuccessful for me.

I am resorting to keeping a clone on a raspberrypi and executing "git pull" before mirror copying to my Amiga system (which is usually a full clone archive copy and unpack)

"sgit pull" is an essential operation...why is it missing ?

**Comment by sba1** [comment]
I never use git pull. Simply as it is the same as git fetch followed by git merge or git rebase and therefore git pull wasn't not top priority (again, contributions are highly welcome!). 

What does
 sgit branch -a
tell?

BTW
sgit merge master will merge your local master branch to the current one. If this is your current branch anyway, it doesn't make much sense to call it.

**Comment by ghost** [comment]
Would love to contribute...  don't have my own linux system for running the build system,
  I would need native equal target build support to do anything

sgit branch -a
- master
  origin/master
  origin/gh-pages

**Comment by sba1** [comment]
From your mails I suppose that you have at least a raspberry. It should be fairly easy to set up a cross compiler environment (I did it myself).

And if you would tell what sgit branch -a tell we can continue exploring why the merging doesn't work.

**Comment by ghost** [comment]
master \ origin/master \ origin/gh-pages \ origin/minimal

these are the 4 branches currently in the Perception-IME repository here on github with a \* on the master branch after cloning a new copy after my collaborators changes.

I'd certainly like to be able to fetch and update locally if possible.

**Comment by salass00** [comment]
If you're not going to implement the pull command maybe you could add to the readme what the equivalent to pull would be using fetch and merge commands.

While "git fetch github.com/username/repo.git" seems to work fine (at least it seems to do something and it doesn't report any errors) I have no idea where to it performs this fetch or how I'm supposed to use it with the merge command.

The merge command seems to expect a commit id but how am I supposed to get that information when git log only shows the commits in the current local branch?

**Comment by sba1** [comment]
Use use the branch name, e.g., `orgin/master` where origin is the remote name and master the branch name. As this is git knowledge, I don't think it is necessary to document it in this project.. See e.g., https://stackoverflow.com/questions/3419658/understanding-git-fetch-then-merge or https://www.kernel.org/pub/software/scm/git/docs/git-pull.html for an describtion what `git pull` does.

There will be a `git pull` at some time, but it is not top priority. Personally, I don't use `git pull` at all because I like to have more control. Contributions are of course welcome.

**Comment by salass00** [comment]
Just tried and the commands:

sgit fetch origin
sgit merge origin/master

seem to have done the job.
