### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by ghost** [sba1/simplegit#12]
is there ever going to be the option to build sgit 100% natively on an AOS4 system for AOS4 or will it remain forever crippled by dedicated use of cross-compilation?

**Comment by sba1** [comment]
This has medium priority for myself, but contributions are highly welcome!

**Comment by ghost** [comment]
Love to,  if I can ever work out what the essentials are of a functinal cross-compiler that doesn't error out during building from source

**Comment by sba1** [comment]
There is now a simple build framework that doesn't rely on cmake at least. It does not yet work out of the box (because of usage of submodules) but it should make it easier to compile it natively.

**Comment by sba1** [comment]
Closing this as nightly regularly use these scripts.
