### ISSUE TITLE
version information error

### ISSUE THREAD

**Issue by raziel-** [sba1/simplegit#14]
sgit version
libgit error (2): Failed to resolve path '.git': No such file or directory

sgit -version
libgit error (2): Failed to resolve path '.git': No such file or directory

sgit --version
libgit error (2): Failed to resolve path '.git': No such file or directory

sgit-20150331-000517
AmigaOS4

**Comment by sba1** [comment]
> sgit version
> libgit error (2): Failed to resolve path 'git': No such file or
> directory
> 
> sgit -version
> libgit error (2): Failed to resolve path 'git': No such file or
> directory
> 
> sgit --version
> libgit error (2): Failed to resolve path 'git': No such file or
> directory
> 
> sgit-20150331-000517
> AmigaOS4

Works here with the current version (use "sgit version"). Please test 
with it (should appear soon, or go to the Jenkins site)

**Comment by raziel-** [comment]
Oh i missed the latest additions...

sgit-20151231-000535

sgit version
libgit error (2): Failed to resolve path '.git': No such file or directory

I think i know why it happens.
Clearly it can't find a .sgit subdir

So if i use the command from ram: or in a dir with no .git subdir the error pops up.

If i switch to a dir with sgit checked out code it will work, probably also with the earlier versions.

Don't think there is a solution for that, maybe add informative feedback that sgit needs to be in a source code dir?

**Comment by sba1** [comment]
sgit version should also work without any .git dir. So yes, it is a bug and should be fixed. Thanks.

**Comment by raziel-** [comment]
Fixed in 0.536

Thank you :-)

sgit version 0.536
using libgit2 0.23.4 and OpenSSL 1.0.1q 3 Dec 2015

**Comment by sba1** [comment]
Thanks for testing.
