### ISSUE TITLE
tag command broken

### ISSUE THREAD

**Issue by Futaura** [sba1/simplegit#18]
It seems "sgit tag" is broken when it comes to deleting and creating tags - all that works is listing existing tags.

The problem seems to be at https://github.com/sba1/simplegit/blob/master/src/builtin/tag.c#L51 - the wrong arguments are selected.  Here's the output from sgit for delete and create:

8> sgit tag -d V2017
libgit error (4): Reference 'refs/tags/-d' not found

8> sgit tag V2018
assertion "repo && tag_name && target" failed: file "/home/sba/amiga/git2.git/libgit2/src/tag.c", line 250

**Comment by sba1** [comment]
I switched the args. This hopefully fixes the command.

**Comment by sba1** [comment]
I'll assume that it is fixed and so I close this.
