### ISSUE TITLE
Feature Request: "remote" would be nice

### ISSUE THREAD

**Issue by raziel-** [sba1/simplegit#19]
sgit remote add user

would be nice to have to merge in and test PR's that are not yet in main

**Comment by raziel-** [comment]
Sorry for the hassle, have only now been able to test this.

Thanks for the addition, but i may be doing something wrong as it doesn't work here unfortunately.

I'm trying to add an engine to scummvm that is not yet in main.
Engine is here: https://github.com/Strangerke/scummvm/tree/lalaw

When i'm in my scummvm main tree, i'm using this line to set the new remote:
sgit remote add origin https://github.com/Strangerke/scummvm/tree/lalaw.git

But when i'm trying to fetch it with
sgit remote -v
(as per documentation at https://help.github.com/articles/adding-a-remote/) i get this error message
sub command is not valid

Am i doing somwthing wrong?

**Comment by sba1** [comment]
With `git remote -v` you don't fetch/update from the remote repo, instead you list all remotes. This option of the subcommand is most likely not supported as this was only about "remote add". Please file another Issue to get the new options if desired.

If you want to fetch, you should use `sgit fetch <remote>`.
