### ISSUE TITLE
sgit diff crashed with a nullptr DSI.

### ISSUE THREAD

**Issue by DaniWe** [sba1/simplegit#2]
I changed one file, like 15-20 lines and did a diff and here's what I got (slightly edited):

$ sgit status
On branch master

Changes not staged for commit:

modified: src/annMain.c

Untracked files:

$ sgit diff  src/annMain.c
-3
libgit error (4): Reference 'src/annMain.c' not found

Crash log for task "git"
Generated by GrimReaper 53.16
Crash occured in module git at address 0x7E95688C
Type of crash: DSI (Data Storage Interrupt) exception

Register dump:
GPR (General Purpose Registers):
   0: 7E8D5DB4 59FA8BE0 00000000 0000000A 59FA8580 00000000 14934116 00000000 
   8: 00000036 0000000A 0223A734 59FA8C30 24842024 58BE6DE4 00000000 59F68680 
  16: 7E8CB2F8 00000001 4DBFA760 59F8BF28 02B30000 02B30000 00000000 00000014 
  24: 6FF8F000 00000003 48844088 00000000 02B30000 02B30000 59F8BF00 59FA8BE0 

FPR (Floating Point Registers, NaN = Not a Number):
   0:              nan               20              nan     -1.0802e+307 
   4:    -5.17539e+245              nan     -1.0802e+307     -1.0802e+307 
   8:     -1.0802e+307              581                5               55 
  12:      2.14748e+09               11                0                0 
  16:                0                0                0                0 
  20:                0                0                0                0 
  24:                0                0                0                0 
  28:                0                0                0                0 

FPSCR (Floating Point Status and Control Register): 0x82020000

SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0000B030
                Condition (cr) : 0x02B30000
      Instruction Pointer (ip) : 0x7E95688C
       Xtended Exception (xer) : 0x02B30000
                   Count (ctr) : 0x59F8BF00
                     Link (lr) : 0x59FA8BE0
            DSI Status (dsisr) : 0x020462B0
            Data Address (dar) : 0x00000000

680x0 emulated registers:
DATA: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 

Symbol info:
Instruction pointer 0x7E95688C belongs to module "git" (HUNK/Kickstart)

Stack trace:
    module git at 0x7E95688C (section 5 @ 0x8B868)
    module git at 0x7E95873C (section 5 @ 0x8D718)
    module git at 0x7E8D5DB4 (section 5 @ 0xAD90)
    module git at 0x7E8CB56C (section 5 @ 0x548)
    native kernel module newlib.library.kmod+0x000020a4
    native kernel module newlib.library.kmod+0x00002d0c
    native kernel module newlib.library.kmod+0x00002ee8
    _start()+0x170 (section 1 @ 0x16C)
    native kernel module dos.library.kmod+0x00024bb0
    native kernel module kernel+0x00042514
    native kernel module kernel+0x00042594

PPC disassembly:
 7e956884: 907f0008   stw               r3,8(r31)
 7e956888: 813f0008   lwz               r9,8(r31)
*7e95688c: 81290000   lwz               r9,0(r9)
 7e956890: 3929ffff   subi              r9,r9,1
 7e956894: 815f0008   lwz               r10,8(r31)

System information:

CPU 
 Model: P.A. Semi PWRficient PA6T-1682M VB1 
 CPU speed: 1800 MHz 
 FSB speed: 900 MHz 
 Extensions: altivec 

Machine 
 Machine name: AmigaOne X1000 
 Memory: 2097152 KB 
 Extensions: bus.pci bus.pcie

**Comment by sba1** [comment]
I've just fixed some diff related stuff. Please try again. Note that subsets of the repo is not supported yet.

**Comment by DaniWe** [comment]
Thanks!
Subsets; does that mean individual files, or just subdirectories?
I diff individual files a lot at work...

**Comment by sba1** [comment]
Yes, one cannot restrict the diff to certain paths for now. I'm going to close this as the crash is fixed.

**Comment by DaniWe** [comment]
Maybe not so important, but still crashes if you give it a path:
$ sgit diff src/annMain.c 
--DSI here that can be ignored--
libgit error (4): Revspec 'src/annMain.c' not found.
$

**Comment by sba1** [comment]
Crashes are always important. Should be fixed now.
