### ISSUE TITLE
sgit checkout file returns -3

### ISSUE THREAD

**Issue by capehill** [sba1/simplegit#20]
Trying to "sgit checkout something" to revert changes gives

libgit error (4). File not found.

**Comment by sba1** [comment]
At the moment you can checkout only branches and not individual paths.

**Comment by sba1** [comment]
I implemented the feature for a single file.

**Comment by capehill** [comment]
Thanks for the support: I tried new version, it works on repo root but unfortunately fails with "sgit path/to/file". Is this possible to implement too?

**Comment by sba1** [comment]
Can you paste the error message please?

**Comment by capehill** [comment]
Sure. Please note that even though the 3rd attempt looked better, file is still in modified state.

2.Code:git/ioquake3> sgit checkout code/tools/lcc/COPYRIGHT
Error code -3
libgit error (4): Reference 'code/tools/lcc/COPYRIGHT' not found

2.Code:git/ioquake3> sgit checkout "code/tools/lcc/COPYRIGHT"
Error code -3
libgit error (4): Reference 'code/tools/lcc/COPYRIGHT' not found

2.Code:git/ioquake3> sgit checkout ./code/tools/lcc/COPYRIGHT
Checking out ./code/tools/lcc/COPYRIGHT

**Comment by sba1** [comment]
Please try with the latest version. If it is still not working, please file a new Issue.

**Comment by capehill** [comment]
It works now well.

Tried with:

path/to/file
path/to
file

All worked nicely. Thanks!
