### ISSUE TITLE
FR: Implement sgit remote -v

### ISSUE THREAD

**Issue by raziel-** [sba1/simplegit#22]
Please add "remote -v" as per documentation from https://help.github.com/articles/adding-a-remote/

Followup to #19

Thanks a lot

**Comment by sba1** [comment]
I'll add this. However,note that you can just view the contents of `.git/config` to see a list of the remotes (and more).

**Comment by raziel-** [comment]
I'm sorry if i'm a PITA but using this in the way it is meant by the docs i get this error message on trying to fetch the remote

sgit fetch lalaw
Fetching lalaw for repo at /Development/Coding/Ports/scummvm_remote_test/.git/
libgit error (12): Unexpected HTTP status code: 404

I tried with remotes http: and https: like this
sgit remote -v
lalaw	https://github.com/strangerke/scummvm/tree/lalaw.git (fetch)
lalaw	https://github.com/strangerke/scummvm/tree/lalaw.git (push)
lalaw1	http://github.com/strangerke/scummvm/tree/lalaw (fetch)
lalaw1	http://github.com/strangerke/scummvm/tree/lalaw (push)

Anything i'm doing terribly wrong?

**Comment by sba1** [comment]
> I tried with remotes http: and https: like this
> sgit remote -v
> lalaw https://github.com/strangerke/scummvm/tree/lalaw.git (fetch)
> lalaw https://github.com/strangerke/scummvm/tree/lalaw.git (push)
> lalaw1 http://github.com/strangerke/scummvm/tree/lalaw [1] (fetch)
> lalaw1 http://github.com/strangerke/scummvm/tree/lalaw [1] (push)
> 
> Anything i'm doing terribly wrong?

The URL looks wrong. It should be https://github.com/strangerke/scummvm. 
The lalaw is a branch. Use checkout after fetching the repo.

Hope this helps.

**Comment by raziel-** [comment]
That did it, yes, but now i'm stuck at another level as i don't really know how to "merge" one of those branches into master

sgit fetch lalaw2
Fetching lalaw2 for repo at /Development/Coding/Ports/scummvm_remote_test/.git/
remote: Counting objects: 2210, done.
remote: Compressing objects: 100% (509/509), done.
remote: Total 2210 (delta 1818), reused 2080 (delta 1700), pack-reused 0
Received 2210/2210 objects in 0 bytes (used 134 local objects)
[new]     040d8456cef35d1147ae refs/remotes/lalaw2/Nancy
[new]     4148ba60a0f739e972be refs/remotes/lalaw2/branch-1-5-tony
[new]     e14e7992cc95dce8c78d refs/remotes/lalaw2/gnap
[new]     1ce445af50f24633d68f refs/remotes/lalaw2/lalaw
[new]     1b24079f71a9af7c2a27 refs/remotes/lalaw2/master
[new]     08589a2baacf5c52aae6 refs/remotes/lalaw2/sandbox

Sorry for educating a noob :-/

**Comment by sba1** [comment]
Do you want to merge or checkout the changes? You checkout a branch via `git checkout <branch>`, e.g., `git checkout lalaw`. If you want to really merge a remote branch, e.g., `lalaw` from the `lalaw2` remote, you would use e.g. `git merge lalaw2/lalaw`.

I suggest to get used to the most important commands, you could try https://try.github.io
