### ISSUE TITLE
[Enhancement] Update to libgit2 v0.26.0 or later

### ISSUE THREAD

**Issue by mankash** [sba1/simplegit#24]
Newer versions of libgit2 have sha1 collision detection and other great features. Would be great if you could update to the same. 

Thanks

**Comment by mankash** [comment]
Hello @sba1 - Do you have an update of the lingit2 module in the roadmap? Newer versions of libgit2 have sha1 collision detection and other great features.

Thank you for this very useful software

**Comment by sba1** [comment]
Am 2017-09-07 22:45, schrieb Manohar Kashyap:
> Hello @sba1 [1] - Do you have an update of the lingit2 module in the
> roadmap? Newer versions of libgit2 have sha1 collision detection and
> other great features.

It is planned, but I don't know when I find the time. It also depends 
how well the AmigaOS patches apply to the baseline and if other ones are 
required. Unfortunately, I haven't contributed many of them back to 
mainline.

**Comment by sba1** [comment]
I've just bumped libgit2 to latest 0.26. Thanks for your report.

**Comment by kashDisk** [comment]
@sba1  - Thanks for addressing the request.

**Comment by mankash** [comment]
@sba1  - Thanks for addressing the request
