### ISSUE TITLE
OpenSSL not found 

### ISSUE THREAD

**Issue by tpimh** [sba1/simplegit#25]
I don't know the reason of this error, tried multiple different distributions, dev packages for openssl are installed. Because of this error libgit2 is not being built. Here is the output:

    echo "#define SIMPLEGIT_REVISION_STRING \"598\"" >/path/to/simplegit/build/sgit-version.h
    echo "#define SIMPLEGIT_DATE_STRING \"30.08.2017\"" >>/path/to/simplegit/build/sgit-version.h
    cd "/path/to/simplegit/build" && cmake "/path/to/simplegit/CMake" -DCMAKE_C_FLAGS="\
	    -imacros /path/to/simplegit/build/sgit-version.h"
    -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES) (found version "1.0.2g")
    -- Configuring done
    CMake Warning (dev) at CMakeLists.txt:86 (add_dependencies):
      Policy CMP0046 is not set: Error on non-existent dependency in
      add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
      Use the cmake_policy command to set the policy and suppress this warning.

      The dependency target "build_libgit2" of target "sgit-bin" does not exist.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Generating done

If I try to build libgit2 separately, it builds successfully.

**Comment by sba1** [comment]
You could try building libgit2 first, e.g.,
```
make libgit2
make
```

The dependency between sgit and libgit2 is currently not encoded in the makefile.

**Comment by tpimh** [comment]
It seems to be two different errors. First is not being able to locate OpenSSL. Removing `SET(CMAKE_SYSTEM_NAME "Generic")` from Makefile fixes it. The second is related to libgit2 not being built, the rule for building it is commented out, so I comment out the line `add_dependencies(sgit-bin build_libgit2)` so this error (just a warning actually) is not triggered.

So now I do the following to build:

    git submodule init
    git submodule update
    mkdir libgit2/build
    cd libgit2/build
    cmake -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -G Ninja ..
    ninja
    cd ../..
    echo "#define SIMPLEGIT_REVISION_STRING \"$(git rev-list HEAD --count)\""  > sgit-version.h
    echo "#define SIMPLEGIT_DATE_STRING \"$(date +%d.%m.%Y)\"" >> sgit-version.h
    mkdir build
    cd build
    cmake ../CMake
    cmake -DCMAKE_C_FLAGS="-imacros sgit-version.h" ../CMake
    make

But there are still some problems to be fixed:
 - static linking doesn't work
 - ninja build fails with "depfile has multiple output paths"
 - having to manually generate `sgit-version.h` (I wonder if it's possible to do it with cmake)
 - having to run cmake twice to add CFLAGS after compiler is detected (using absolute path should fix it)

**Comment by sba1** [comment]
Well, it would be possible to drop cmake for sgit in favour of good old make (I did so of the AmigaOS version but the case is somewhat simpler here). At least I'm feeling much more comfortable with it (hence the current strange make/cmake hybrid).

The way I build it locally (basically just using the makefile targets) works though. But I have not tried ninja.

In any case, improvements to the build process for non-amigaoid targets are welcome.

**Comment by tpimh** [comment]
Solved it. I successfully built sgit with external libgit2 on x86_64.
