### ISSUE TITLE
Broken 0.611

### ISSUE THREAD

**Issue by raziel-** [sba1/simplegit#28]
The jenkins build 0.611 (https://sonumina.de/jenkins/job/sgit.amiga/lastSuccessfulBuild/artifact/dist/sgit-20171218-000611.lha) is broken.

Updating (fetching) already checked out projects result in an unknown libgit error (12), *if* there is stuff to update. Otherwise it will work normal.

Went back to 0.585 which works fine

**Comment by capehill** [comment]
Same issue here. Fetching updates from ScummVM project gives error 12. I haven't tried re-cloning yet (it's a huge project).

**Comment by raziel-** [comment]
cloning still works with 0.611
It seems only fetching is affected

**Comment by sba1** [comment]
It works here at least on Linux. Can you paste a Snoopy log?

**Comment by raziel-** [comment]
It's one strange error.

I just tried with the residualvm project and it works there just fine with 0.611 (fetching).
I then tried immediately on the scummvm main tree, where it errored out again. (log attached)

**Comment by raziel-** [comment]
OK, log is too big and long, any place i can upload it to?

OS4Depot and pastebin doesn't work either

**Comment by raziel-** [comment]
Sent to you by mail...Odyssey is getting worse to use by the day...i can't use the "Edit" button

**Comment by sba1** [comment]
Unfortunately, I'm still unable to reproduce this. I tried the scummvm repo during the last days.

**Comment by raziel-** [comment]
Snce there is 0.623 out and since i forgot how to get 0.611 ;-) and since the error is gone with the latest revision, i think it's fine if this gets closed.

**Comment by sba1** [comment]
Great!
