### ISSUE TITLE
Don't create dummy commits (either empty or misconfigured)

### ISSUE THREAD

**Issue by ksdhans** [sba1/simplegit#29]
SimpleGit creates a dummy commit even if there are no changes staged. It really should give an error message and give you a chance to fix it.

Likewise, it'll warn you when the author and/or committer information isn't set, but will create a commit with a dummy author and email address anyway.

**Comment by sba1** [comment]
Which version are you using? I believe that this is not the case in the current version.

The current version is always available from here:
 https://sonumina.de/jenkins/job/sgit.amiga/

**Comment by ksdhans** [comment]
I'm using the version on os4depot. It's dated: 2 Jan 2016.

I'll update and try again with the current version.

**Comment by ksdhans** [comment]
Okay, just tested with the latest version, and it does indeed prevent you from creating dummy commits.
