### ISSUE TITLE
Add support for add -A (and/or sgit commit -a)

### ISSUE THREAD

**Issue by ksdhans** [sba1/simplegit#32]
SGit currently doesn't support the -A option for "add," or the -a option for commit which will commit all changes without having to manually add each one. 

Having to execute sgit add for every file that changed is very tedious. So, please add support for the "commit all" options to match regular git.

**Comment by sba1** [comment]
It should be possible to add directories, e.g., also the root. E.g., ```sgit add .``` will add all files from the current directories. There is no need to specify the files manually. However, it does not behave as newer original git versions yet, as it won't remove deleted files from the index.

**Comment by sba1** [comment]
The ```sgit add``` command should now behave more like modern ```git add```, i.e., removed files will be removed from index if the pathspec match them. So the requested ```-A``` option is not necessary (expect that you have to specify a path like ```.```).
