### ISSUE TITLE
Is it time for a new release?

### ISSUE THREAD

**Issue by tpimh** [sba1/simplegit#33]
Last release was from 2015. There will be a new one?

**Comment by sba1** [comment]
There is no plan for an official release. It is mostly continuously delivery. For what platform do you need binaries?

**Comment by tpimh** [comment]
I want a source tarball, so I can build my own binaries for RISC-V and x86_64. If there are no plans to release soon, I will just build from master branch.
I also want to link dynamically with libgit2. Is it possible to use upsteram libgit2 with sgit on x86_64? Are the changes in your fork amiga-specific or do they add some unique functions that sgit relies on? If yes, do you have any plans upstreaming those?

**Comment by sba1** [comment]
The libgit2 changes are mostly only AmigaOS related, at least that is the idea. I plan to upstream them as soon as I have cleaned them up.

So in essence, linking against the upstream libgit2 should work for the standard platforms, if it is the same release version (0.26 as for now). If that should does not work, it is a bug.

**Comment by tpimh** [comment]
Thank you! I will try to build with upstream libgit2 on x86_64 this weekend.

**Comment by sba1** [comment]
Great! So I'll close this. If you encounter any problems, please file a new Issue.
