### ISSUE TITLE
New GitHub project... changes not committing back to the server...

### ISSUE THREAD

**Issue by ghost** [sba1/simplegit#5]
I'm in the middle of migrating "perception-ime" from code.google.com to github.com,
"/p/perception-ime" for the old server root,  "/Belxjander/Perception-IME" for the new server root.

Using "sgit clone https://github.com/Belxjander/Perception-IME.git" works fine for the blank repo,

Using "sgit commit" and "sgit push origin" after making changes ask for username/password (github login I believe).
  Result of the push origin is to give me a command prompt and the server-side repository clone/checkout remains clean.

Am I not following the correct git workflow or have I completely missed something in trying to commit changes and push them to the github server?

**Comment by sba1** [comment]
If you specify the branch to push, does it work then?

E.g.,

```
1.> sgit push origin master
```

**Comment by ghost** [comment]
That improved things,  also needed to edit the .git/config file to change the origin path from "git://" to "https://" protocol in the URL specification
