### ISSUE TITLE
Datestamps within a repository are all reset to "Amiga Year Zero" (~January 1st, 1970)

### ISSUE THREAD

**Issue by ghost** [sba1/simplegit#6]
Is there any means to reset the dates on the affected files so that they are then updated when pushing updates to the repository?

What information about my system do I need to check?

Do I need to custom build simplegit from sources to have a working client?

Has anyone else run into datestamps only being locally valid?

System Information:

  Hardware = sam440 with 2x 500GB drives,
  Software = AmigaOS 4.1.6 with AmiUpdates applied.
  HDD partitions are Workbench = FFS/07(2GB) with SFS/02(20,60,127,127,127,82,60,60 GBs each)

the local development partition is working from SFS

**Comment by sba1** [comment]
Date problem should be fixed.

It happened when no author/committer was configured.
