### ISSUE TITLE
Attempting to "push" modified file changes appears to have no changes saved

### ISSUE THREAD

**Issue by ghost** [sba1/simplegit#7]
modifying the GNUmakefiles for updated paths results in no changes pushed.

sgit commit -m "..."
sgit push origin master

is the workflow being executed with no results being actually pushed to the github server.

possibly related to the files in question all being Jan 1st 197- datestamped?

**Comment by sba1** [comment]
Did you add the file to the index before?

sgit add GNUmakefile

**Comment by sba1** [comment]
Closing this as it is old. Please file a new issue if this problem still exists.
