### ISSUE TITLE
Have no git pull

### ISSUE THREAD

**Issue by xiangism** [sba1/simplegit#9]
Have no git pull, what are you replace the "git pull"?
What version of the libgit2 are you work on?  On the new version of the libgit2 , couldn't comiple the simplegit...

**Comment by sba1** [comment]
You can do a 'git fetch' followed by a 'git merge' or 'git rebease'.

The simplegit tool is based on 0.22 of libgit2 but an update is due.

**Comment by xiangism** [comment]
Yeah, I get it. Thanks~~

**Comment by xiangism** [comment]
@sba1  I have success called cmd_fetch() , and I can't call cmd_rebase() success.
This is my code:

```
void TestRebase()
{
    git_repository *repo = NULL;

    git_libgit2_init();
    git_repository_open(&repo, "LiteMath/.git");

    cmd_rebase(repo);

    git_repository_free(repo);
    git_libgit2_shutdown();
}
```

In the function cmd_rebase(), I delete the params "argc"and "argv", and  set  
`upstream_str="rebase"`
when the prgram execute at
`if ((err = git_reference_dwim(&upstream_ref, repo, upstream_str)))` , it return -3. 
I think It is error the value of "upstream_str" , what value would I set it? I just want it have the same action of "git pull" .

Thanks ~~

**Comment by xiangism** [comment]
Oh, I get it, set  the value of  "FETCH_HEAD"  ^_^

**Comment by xiangism** [comment]
I have a problem when call "cmd_push". I remove the params "argc" and "argv" again, and replace argv[i] of "orgin" in "loop for".
when call git_remote_get_push_refspecs(), the value of cfg_refs.count is 0, so it print "No refspec given and no refspec configured. Pushing is probably a noop".
when call git_remote_push(), the return value is -1, I called giterr_last(), the error message is "Request failed with status code: 401".
How can I do??
ps: And I find "git_remote_set_callbacks()"  can't find in libgit2, so I replace it of "git_remote_init_callbacks()"

**Comment by xiangism** [comment]
I have solve the problem, thanks ~~
